sudo: required
services:
  - docker

before_install:
  - docker build -t adamfriedl/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run adamfriedl/react-test npm test -- --coverage

after_success:
  - docker build -t adamfriedl/multi-client ./client
  - docker build -t adamfriedl/multi-nginx ./nginx
  - docker build -t adamfriedl/multi-server ./server
  - docker build -t adamfriedl/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to Docker Hub
  - docker push adamfriedl/multi-client
  - docker push adamfriedl/multi-nginx
  - docker push adamfriedl/multi-server
  - docker push adamfriedl/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-904601858425
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
